### ISSUE TITLE
给你了一个star

### ISSUE THREAD

**Issue by 88assistane** [zhahoi/Nanodet-YoloV8-Pose-MeterReader#1]
尊敬的作者你好，我感觉你的这个代码有用，麻烦将训练数据集和数据标注细节发给我一份，谢谢！

**Comment by zhahoi** [comment]
你好，请留下一个邮箱地址，我周一上班整理之后给你发。

**Comment by zhahoi** [comment]
> 尊敬的作者你好，我感觉你的这个代码有用，麻烦将训练数据集和数据标注细节发给我一份，谢谢！

可以从这个百度网盘地址下载到：通过网盘分享的文件：指针仪表检测数据集与标注细节.zip
链接: https://pan.baidu.com/s/19I3vs1c01DAdB2V3G67RlA?pwd=383j 提取码: 383j

**Comment by zhahoi** [comment]
从上面的百度云链接可以下载到NanodetPlus目标检测数据集和Yolov8Pose关键点检测数据集，同时文件夹里还有一些数据标注的细节。我准备关闭这个issue了，有问题，可以在后面提问。

**Comment by 88assistane** [comment]
好的，感谢！

**Comment by 88assistane** [comment]
您好！是否可以将整个python训练工程发一份？

**Comment by zhahoi** [comment]
训练工程ReadMe有百度云链接，你可以自己下载。

**Comment by 88assistane** [comment]
好的，谢谢！

**Comment by 88assistane** [comment]
Dataset 'ultralytics/cfg/datasets/coco8-pose.yaml' images not found ⚠️, missing path 'C:\Github\ultralytics\ultralytics\data-pose\images\val'
相对路径和绝对路径都试过了，都不对，请问是什么原因？

**Comment by zhahoi** [comment]
我这个路径是基于我电脑的文件夹命名来的，你得设置成自己的
![image](https://github.com/user-attachments/assets/7a15ea4b-643d-4786-9600-775f5a396b75)

**Comment by 88assistane** [comment]
和你的目录是一致的。

**Comment by zhahoi** [comment]
发出来看看，你的仓库路径是C:/Github/ultralytics吗？

**Comment by 88assistane** [comment]
路径的问题我已经解决了。

**Comment by 88assistane** [comment]
train: WARNING ⚠️ C:\datasets\images\train\aug_new_001.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1523      1.0754      1.6954      1.8491           2           2]
这个是什么原因？

**Comment by zhahoi** [comment]
你好，遇到问题可以尝试自己在搜索引擎搜索，尝试自己解决问题，相信你的能力会提升得更快。：）
