### ISSUE TITLE
adout pt2ncnn

### ISSUE THREAD

**Issue by Kk875** [zhahoi/Nanodet-YoloV8-Pose-MeterReader#2]
您好，已经star了，有个问题想问，如何将模型从pt格式转换为ncnn格式呢？

**Comment by zhahoi** [comment]
yolov8有可以直接从pt转换到ncnn的python代码。我更常用的方法是先将pt转换成onnx，再使用ncnn库里面的onnx2ncnn转换成ncnn。你可以用yolov8自带的转换代码一键转换试试。我记得我转换的时候挺丝滑的，没有遇到什么问题。
![微信截图_20241015155619](https://github.com/user-attachments/assets/5091acb8-aa30-4657-a299-2635d85d899c)

如果你想要和我一样从onnx转ncnn，可以参考下面的博客：https://blog.csdn.net/xian0710830114/article/details/121141409。

转换存在问题的化，可以发出来，相互沟通。

**Comment by zhahoi** [comment]
不知道为啥csdn地址会被和谐：https://blog.csdn.net/xian0710830114/article/details/121141409

**Comment by Kk875** [comment]
> 不知道为啥csdn地址会被和谐：https://blog.csdn.net/xian0710830114/article/details/121141409
好的 我试试  谢谢您！

**Comment by zhahoi** [comment]
![微信截图_20241015155619](https://github.com/user-attachments/assets/1216b71a-b745-40c3-a970-79b562a38cfa)
我好像没查到具体的yolov8版本，但是看我的下载日期的话大概是这几个版本内的。我使用的是官方的转onnx的代码，然后我的onnx可视化是存在三个输出的。不知道是不是你的Yolov8版本过低的问题。
![微信截图_20241015173100](https://github.com/user-attachments/assets/6005ac0e-896b-403b-8927-265bc2a8fdae)

**Comment by zhahoi** [comment]
![微信截图_20241015173654](https://github.com/user-attachments/assets/db768393-ac75-4e96-96c2-858baabb9d8e)
我简单推测了一下我的ultralytics版本大概是这几个，你的ultralytics版本应该太低了，不知道是不是变动比较大。你试着更新一下ultralytics版本看看，ncnn部分c++的推理代码我参考别人的github仓库，我应该在readme列出来了，如果有疑问的，可以去看看他的代码。

**Comment by Kk875** [comment]
> ![微信截图_20241015173654](https://private-user-images.githubusercontent.com/104057195/376551637-db768393-ac75-4e96-96c2-858baabb9d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODkwMDUsIm5iZiI6MTcyODk4ODcwNSwicGF0aCI6Ii8xMDQwNTcxOTUvMzc2NTUxNjM3LWRiNzY4MzkzLWFjNzUtNGU5Ni05NmMyLTg1OGJhYWJiOWQ4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMDM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2FiZWUxZWFjNGRjMjc3ZWU5ODU1ZTRkZGU1YzdkZDlhMWRmMjE1MzFjNzFmY2ExYzcxZDJmNmQ1YTQ5Zjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.11DT5Y5wU64lUHikVDw-fHw6bOrv0I8z3YIgIIbircw) 我简单推测了一下我的ultralytics版本大概是这几个，你的ultralytics版本应该太低了，不知道是不是变动比较大。你试着更新一下ultralytics版本看看，ncnn部分c++的推理代码我参考别人的github仓库，我应该在readme列出来了，如果有疑问的，可以去看看他的代码。

您好，在您的Readme中，我并未找到转换相关代码仓库，我升级了我的版本为8.2.70，导出yolov8n-pose官方模型进行测试，结果输出仍然是只有一个，在我的印象中，是需要修改源码中关于输出头部分的代码，才能导出有三个输出的onnx模型
![problem2](https://github.com/user-attachments/assets/52e68237-ea68-455a-9eb5-c0bd72a80390)
并且在8.2.70版本中并没有export_onnx.py以及ncnn文件
![Uploading problem3.jpg…]()

**Comment by Kk875** [comment]
我在ubuntu20.04 中编译运行本仓库中的代码，在修改const float aspectRatioThreshold = 0.60f;之后，代码能正常运行，但是输出的结果完全不对，使用的模型就是本仓库中自带的模型，推理结果如图：
![problem4](https://github.com/user-attachments/assets/52c784eb-aa8b-476f-af0b-b42b7d8ca720)

**Comment by zhahoi** [comment]
你好，yolov8-pose关键点检测部分代码我应该确实有修改（因为之前没把精力放到这个上面，更改的细节可能忘记了），你需要的话我明天把我整个python训练工程给你发一份。另外关于上面推理部分。我关键点检测数据是我自己标注的，主要针对我验收使用的仪表进行标注的（如果推理其他不同型号仪表可能结果会有影响，影响检测精度），如果你想获得更好的检测结果，可以针对你想检测的仪表进行训练标注。

这个链接是我参考的yolov8-pose-ncnn部分代码，你可以看看有没有什么思路：https://github.com/eecn/ncnn-android-yolov8-pose/tree/master/app/src/main/jni

另外，你上面推理的并不是包含仪表的图像，而是已经裁剪ROI之后的图像了，所以显示结果应该不准确。可以换一张包含仪表的整体图像试试。
