### ISSUE TITLE
目标检测的结果一直为1

### ISSUE THREAD

**Issue by GPT0x01** [zhahoi/Nanodet-YoloV8-Pose-MeterReader#4]
<img width="862" alt="71bc631c55faed8fb69c48e200a2efc" src="https://github.com/user-attachments/assets/804363ac-d987-480a-8630-7b217cb1f002">

![image](https://github.com/user-attachments/assets/3d9c6d42-7898-48b3-9e9c-7b4589bc29c5)

![image](https://github.com/user-attachments/assets/edad703c-9d9e-49c9-bf8d-8cb20acfcf10)

您好，我这边用您的代码运行了一下，结果一直识别为1,就是项目中的权重是训练过的吗，还是需要重新训练

**Comment by zhahoi** [comment]
给我个微信联系方式，这样问效率好低

**Comment by GPT0x01** [comment]
> 给我个微信联系方式，这样问效率好低

BaiLanMao 

您可以加下这个微信，谢谢

**Comment by zhahoi** [comment]
项目中的权重应该可以直接使用，你可以把中间的图片处理结果打印出来看看。另外，针对不同量程的仪表，你需要手动修改一下参数。
![微信截图_20241112094802](https://github.com/user-attachments/assets/50f8ec7a-2fd7-416d-9aec-95214794a696)
![微信截图_20241112094651](https://github.com/user-attachments/assets/647dbe2d-b9fd-47ba-8632-72514bc21371)
![微信截图_20241112094520](https://github.com/user-attachments/assets/7dc9c5dd-0443-4e36-a12f-1f573111aa08)
