### ISSUE TITLE
你好，已star,求一份整体的代码，1151329614@qq.com,非常感谢

### ISSUE THREAD

**Issue by Emperor124** [zhahoi/Nanodet-YoloV8-Pose-MeterReader#5]

**Comment by zhahoi** [comment]
你好，README里面我放了训练工程和数据集的百度云链接你可以自助下载，因为数据和工程太大了，邮件并不好发送。

**Comment by Emperor124** [comment]
好的非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月20日(周三) 下午2:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhahoi/Nanodet-YoloV8-Pose-MeterReader] ***@***.***,非常感谢 (Issue #5)




 
你好，README里面我放了训练工程和数据集的百度云链接你可以自助下载，因为数据和工程太大了，邮件并不好发送。
